### ISSUE TITLE
Debian keyring has been expired

### ISSUE THREAD

**Issue by fixmeee** [kopia/kopia#2946] opened 2023-04-16 09:36 UTC
`gpg --show-keys --with-fingerprint /usr/share/keyrings/kopia-keyring.gpg`

pub   rsa4096 2021-04-16 [SC] [expired: 2023-04-16]
      7FB9 9DFD 4780 9F0D 5339  D7D9 2273 699A FD56 A556
uid                      Kopia Builder <builder@kopia.io>

Thank you and BR
Dennis

**Comment by jkowalski** [comment] 2023-04-17 05:37
This is a duplicate of https://github.com/kopia/kopia/issues/2947, closing this one.

**Closed by jkowalski** 2023-04-17 05:37 UTC
