### ISSUE TITLE
Blank window with title "KopiaUI is Loading..."

### ISSUE THREAD

**Issue by probablykasper** [kopia/kopia#2599] opened 2022-11-25 03:37 UTC
My KopiaUI got stuck in this state:
<img width="728" alt="203896077-1e58e7ff-b06a-4fe2-be0e-895c8aee2d4f" src="https://user-images.githubusercontent.com/11315492/203896556-12cda662-778c-4cf3-bb99-112be612f587.png">

Restarting fixed it, but this isn't great as it stopped doing backups without letting me know about it

#2452 seems similar, but that one has to do with removable drives/network shares. I'm using Google Drive through rclone

**Comment by probablykasper** [comment] 2022-12-02 06:06
Is there anything I can do to help debug this? This is happening frequently to me, which unfortunately makes kopia very unreliable.

@jkowalski

**Comment by kapitainsky** [comment] 2022-12-02 19:52
can see the same from time to time (macOS) - no clear pattern yet

**Comment by jkowalski** [comment] 2022-12-03 22:50
You can usually find logs in the "kopia-ui" directory. On Mac this will be `~/Library/Logs/kopia-ui`, let me know if you find a clue there.

Sometimes clues can be found in `~/Library/Logs/kopia`, but I suspect it did not even launch in this case.

**Comment by kapitainsky** [comment] 2022-12-04 09:27
Good thing is that I have found the way to reproduce it reliably (at least one scenario), not so good that it does not trigger any log entries.

How to reproduce? 

Browsing snapshots and clicking at file with zero lengths (file named Icon in this case). Normally UI offers option to restore file and save it. But here all UI become white and unresponsive.

To create Icon file simply paste some image into folder icon in folder "get info" - it creates custom folder icon.

**Comment by probablykasper** [comment] 2022-12-04 21:59
My `kopia-ui/main.log` has a flood of errors. In the span of 10 seconds, I got this one 2721 times:
```
[2022-11-30 20:57:08.681] [info]  error fetching status Error: socket hang up
    at connResetException (node:internal/errors:691:14)
    at TLSSocket.socketOnEnd (node:_http_client:466:23)
    at TLSSocket.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

which ended with this:
```
[2022-11-30 20:57:20.901] [info]  child process exited with code null and signal SIGTERM
```

And got a segmentation fault:
```
[2022-12-02 02:03:36.064] [info]  unexpected fault address 0x307e3994
fatal error: fault

[2022-12-02 02:03:36.069] [info]  [signal SIGSEGV: segmentation violation code=0x1 addr=0x307e3994 pc=0x15b0678]

goroutine 402007 [running]:

[2022-12-02 02:03:36.069] [info]  runtime.throw(
[2022-12-02 02:03:36.070] [info]  {0x20cc749?, 0xc000634a80?})
	/Users/runner/hostedtoolcache/go/1.18.6/x64/src/runtime/panic.go:992 +0x71 fp=0xc041b25ca8 sp=0xc041b25c78 pc=0x10393f1
runtime.sigpanic()
	/Users/runner/hostedtoolcache/go/1.18.6/x64/src/runtime/signal_unix.go:825 +0x2f6 fp=0xc041b25cf8 sp=0xc041b25ca8 pc=0x104f6d6
github.com/kopia/kopia/repo/content/index.indexV2EntryInfo.GetDeleted(...)
	/Users/runner/work/kopia/kopia/repo/content/index/index_v2.go:154
github.com/kopia/kopia/repo/content/index.(*indexV2EntryInfo).GetDeleted(0xd8c8b8a33196f75d?)
	<autogenerated>:1 +0x58 fp=0xc041b25d60 sp=0xc041b25cf8 pc=0x15b0678

[2022-12-02 02:03:36.070] [info]  github.com/kopia/kopia/repo/maintenance.RewriteContents.func1()
	/Users/runner/work/kopia/kopia/repo/maintenance/content_rewrite.go:81 +0x166 fp=0xc041b25fe0 sp=0xc041b25d60 pc=0x1784d26
runtime.goexit()
	/Users/runner/hostedtoolcache/go/1.18.6/x64/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc041b25fe8 sp=0xc041b25fe0 pc=0x106cd41
created by github.com/kopia/kopia/repo/maintenance.RewriteContents
	/Users/runner/work/kopia/kopia/repo/maintenance/content_rewrite.go:68 +0x1be
```

which was followed by more socket hang up spam, which this time ended with:
```
[2022-12-02 02:03:36.220] [info]  child process exited with code 2 and signal null
```

And I got these, those seem like they're probably just from startup:
```
[2022-12-02 07:01:41.493] [error] failed to load
[2022-12-02 07:01:41.996] [info]  reloading
[2022-12-02 07:01:41.997] [error] failed to load
[2022-12-02 07:01:42.500] [info]  reloading
[2022-12-02 07:01:42.500] [error] failed to load
[2022-12-02 07:01:43.005] [info]  reloading
[2022-12-02 07:01:43.005] [error] failed to load
[2022-12-02 07:01:43.511] [info]  reloading
[2022-12-02 07:01:43.511] [error] failed to load
[2022-12-02 07:01:44.016] [info]  reloading
[2022-12-02 07:01:44.017] [error] failed to load
[2022-12-02 07:01:44.520] [info]  reloading
[2022-12-02 07:01:44.520] [error] failed to load
[2022-12-02 07:01:45.025] [info]  reloading
[2022-12-02 07:01:45.025] [error] failed to load
[2022-12-02 07:01:45.530] [info]  reloading
[2022-12-02 07:01:45.530] [error] failed to load
[2022-12-02 07:01:46.034] [info]  reloading
[2022-12-02 07:01:46.034] [error] failed to load
[2022-12-02 07:01:46.438] [info]  stopServer: server not started
[2022-12-02 07:01:48.678] [info]  actuating Server repository
[2022-12-02 07:01:48.680] [info]  stopServer: server not started
[2022-12-02 07:01:48.681] [info]  spawning /Applications/KopiaUI.app/Contents/Resources/server/kopia server --ui --tls-print-server-cert --tls-generate-cert-name=localhost --random-password --random-server-control-password --tls-generate-cert --async-repo-connect --shutdown-on-stdin --address=localhost:0 --config-file /Users/k/Library/Application Support/kopia/repository.config
[2022-12-02 07:01:48.707] [info]  starting polling loop
[2022-12-02 07:01:48.708] [info]  Checking for update
```

And some TLS handshake and "error fetching status":
```
[2022-12-02 07:03:36.891] [info]  2022/12/02 07:03:36 http: TLS handshake error from 127.0.0.1:55733: remote error: tls: unknown certificate

[2022-12-02 07:03:36.892] [debug] accepting server certificate.
[2022-12-02 07:03:36.908] [info]  automatically logging in...
[2022-12-02 15:52:38.079] [warn]  error fetching status Internal Server Error
[2022-12-02 15:52:49.485] [warn]  error fetching status Internal Server Error
[2022-12-02 15:53:00.888] [warn]  error fetching status Internal Server Error
[2022-12-02 15:53:12.270] [warn]  error fetching status Internal Server Error
[2022-12-02 18:03:19.136] [info]  2022/12/02 18:03:19 http: TLS handshake error from 127.0.0.1:52115: remote error: tls: unknown certificate

[2022-12-02 18:03:19.138] [debug] accepting server certificate.
[2022-12-04 22:33:19.484] [info]  actuating Server repository
[2022-12-04 22:33:19.488] [info]  stopServer: server not started
[2022-12-04 22:33:19.489] [info]  spawning /Applications/KopiaUI.app/Contents/Resources/server/kopia server --ui --tls-print-server-cert --tls-generate-cert-name=localhost --random-password --random-server-control-password --tls-generate-cert --async-repo-connect --shutdown-on-stdin --address=localhost:0 --config-file /Users/k/Library/Application Support/kopia/repository.config
[2022-12-04 22:33:19.507] [info]  starting polling loop
[2022-12-04 22:33:19.508] [info]  Checking for update
```

**Comment by jkowalski** [comment] 2022-12-04 22:13
Interesting, loks like you may have a corrupted index file.  What's your backend? Is it a filesystem that may be susceptible to bit flips or something else?

**Comment by probablykasper** [comment] 2022-12-04 22:20
I'm using Google Drive through rsync. Am I able to run a validation on the index file?

When I first backed up, I did get some errors which I think are all due to Kopia not having permissions for the files (https://github.com/kopia/kopia/issues/2587). I think those just got excluded though. Other than that, I haven't gotten any errors from Kopia, including when restoring.

**Comment by jkowalski** [comment] 2022-12-05 00:18
Can you try using kopia CLI `kopia content verify` to see if you get any more information?

**Comment by probablykasper** [comment] 2022-12-05 06:34
Yes tried it, no errors:
```
Listing blobs...
  10000 blobs...
Listed 19920 blobs.
Verifying all contents...
  Verified 1 contents, 0 errors, estimating...
Finished verifying 691448 contents, found 0 errors.
```

**Comment by dson** [comment] 2022-12-27 10:59
I am running into the same issue, where KopiaUI often fails to load.

My `kopia-ui/main.log` contains similar errors:

```
[2022-12-27 10:17:40.149] [info]  unexpected fault address 0x2c70e620
fatal error: fault

[2022-12-27 10:17:40.152] [info]  [signal SIGSEGV: segmentation violation code=0x1 addr=0x2c70e620 pc=0x15b0678]


[2022-12-27 10:17:40.152] [info]  goroutine 179241 [running]:

[2022-12-27 10:17:40.153] [info]  runtime.throw(
[2022-12-27 10:17:40.153] [info]  {0x20cc749?, 0xc00bccd4a0?
[2022-12-27 10:17:40.154] [info]  })
	/Users/runner/hostedtoolcache/go/1.18.6/x64/src/runtime/panic.go:992 +0x71 fp=0xc01d567ca8 sp=0xc01d567c78 pc=0x10393f1
runtime.sigpanic()
	/Users/runner/hostedtoolcache/go/1.18.6/x64/src/runtime/signal_unix.go:825 +0x2f6 fp=0xc01d567cf8 sp=0xc01d567ca8 pc=0x104f6d6

[2022-12-27 10:17:40.154] [info]  github.com/kopia/kopia/repo/content/index.indexV2EntryInfo.GetDeleted(...)
	/Users/runner/work/kopia/kopia/repo/content/index/index_v2.go:154
github.com/kopia/kopia/repo/content/index.(*indexV2EntryInfo).GetDeleted(0x4675af7f589541cf?)
	<autogenerated>:1 +0x58 fp=0xc01d567d60 sp=0xc01d567cf8 pc=0x15b0678
github.com/kopia/kopia/repo/maintenance.RewriteContents.func1()
	/Users/runner/work/kopia/kopia/repo/maintenance/content_rewrite.go:81 +0x166 fp=0xc01d567fe0 sp=0xc01d567d60 pc=0x1784d26
runtime.goexit
[2022-12-27 10:17:40.155] [info]  ()
	/Users/runner/hostedtoolcache/go/1.18.6/x64/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc01d567fe8 sp=0xc01d567fe0 pc=0x106cd41
created by github.com/kopia/kopia/repo/maintenance.RewriteContents
	/Users/runner/work/kopia/kopia/repo/maintenance/content_rewrite.go:68 +0x1be

(...)

[2022-12-27 10:17:40.232] [info]  child process exited with code 2 and signal null
[2022-12-27 10:32:17.966] [error] failed to load
[2022-12-27 10:32:18.467] [info]  reloading
[2022-12-27 10:32:18.468] [error] failed to load
[2022-12-27 10:32:19.038] [info]  reloading

(...)

[2022-12-27 10:43:09.485] [info]  stopServer: server not started
[2022-12-27 10:44:44.050] [info]  actuating Server repository
[2022-12-27 10:44:44.053] [info]  stopServer: server not started
[2022-12-27 10:44:44.054] [info]  spawning /Applications/KopiaUI.app/Contents/Resources/server/kopia server --ui --tls-print-server-cert --tls-generate-cert-name=localhost --random-password --random-server-control-password --tls-generate-cert --async-repo-connect --shutdown-on-stdin --address=localhost:0 --config-file /Users/daniel/Library/Application Support/kopia/repository.config
```

Running `kopia content verify` reports no issues:

```
Listing blobs...
Listed 5492 blobs.
Verifying all contents...
  Verified 1 contents, 0 errors, estimating...
Finished verifying 425251 contents, found 0 errors.
```

Let me know if more logging would be helpful.

**Comment by Ember-ruby** [comment] 2022-12-31 09:55
same here, just happens after a while, restarting it fixes it for a bit, and no errors from `kopia content verify`

to note, it is very inconsistent, it has run for upwards of ten days no issue, down to less than a day

**Comment by probablykasper** [comment] 2023-01-02 09:27
Curious if you have any clues @jkowalski. My only guess is it could be network related. Happy to try a debug build if needed, I run into this bug every few days

**Comment by Ember-ruby** [comment] 2023-01-07 16:20
hm, this also happens with kopia (no ui, but "server" enabled)

looking through the output of `journalctl --no-pager -xe _EXE=/usr/bin/kopia`, it seems to end with 
```
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x7f1960bccdea pc=0x9d6898]
 goroutine 17650912 [running]:
 runtime.throw({0x14fe05a?, 0x19?})
         /opt/hostedtoolcache/go/1.18.6/x64/src/runtime/panic.go:992 +0x71 fp=0xc006517ca8 sp=0xc006517c78 pc=0x438891
 runtime.sigpanic()
         /opt/hostedtoolcache/go/1.18.6/x64/src/runtime/signal_unix.go:825 +0x2ec fp=0xc006517cf8 sp=0xc006517ca8 pc=0x44ea8c
 github.com/kopia/kopia/repo/content/index.indexV2EntryInfo.GetDeleted(...)
         /home/runner/work/kopia/kopia/repo/content/index/index_v2.go:154
 github.com/kopia/kopia/repo/content/index.(*indexV2EntryInfo).GetDeleted(0xc89515767dc735?)
         <autogenerated>:1 +0x58 fp=0xc006517d60 sp=0xc006517cf8 pc=0x9d6898
 github.com/kopia/kopia/repo/maintenance.RewriteContents.func1()
         /home/runner/work/kopia/kopia/repo/maintenance/content_rewrite.go:81 +0x166 fp=0xc006517fe0 sp=0xc006517d60 pc=0xbabae6
 runtime.goexit()
         /opt/hostedtoolcache/go/1.18.6/x64/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc006517fe8 sp=0xc006517fe0 pc=0x46b961
 created by github.com/kopia/kopia/repo/maintenance.RewriteContents
         /home/runner/work/kopia/kopia/repo/maintenance/content_rewrite.go:68 +0x1be
```

**Comment by LinuxOnTheDesktop** [comment] 2023-04-15 00:25
Just now I too experienced this - on Windows. I have not encountered it before. Recently I upgraded to Kopia version 0.13.0-rc1. Closing the window and re-opening it did not help. Terminating and reloading the whole program _did_ help.

**Comment by dominikmayer** [comment] 2023-08-28 08:02
While the root cause is still open, is there at least a chance to include a workaround?

Can Kopia UI monitor if the kopia process is running and either restart it or at least change the taskbar icon so the user can see that there is an issue without having to open Kopia UI every couple of hours?

**Comment by kah-ell** [comment] 2023-09-02 12:14
Happens to me too, kopia-ui on Ubuntu 20.04. It has run for months without any problems, but every now and then it hangs with the blank UI described in this issue and no backups are run anymore. A restart of the GUI fixes it, but lately it has been hanging every couple of days...

It really takes away from the otherwise cozy feeling of having an hourly backup running. "kopia content verify" returned with zero errors.

Logs are full of paragraphs like this, countless [runnable]'s and [semacquire]'s:
```
goroutine 19630917 [runnable]:
github.com/kopia/kopia/repo/maintenance.RewriteContents.func1()
	/home/runner/work/kopia/kopia/repo/maintenance/content_rewrite.go:71 +0x117
created by github.com/kopia/kopia/repo/maintenance.RewriteContents
	/home/runner/work/kopia/kopia/repo/maintenance/content_rewrite.go:68 +0x1be

goroutine 19630988 [semacquire]:
sync.runtime_SemacquireMutex(0x10000?, 0xa8?, 0x1?)
	/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc006a229ac)
	/opt/hostedtoolcache/go/1.18.6/x64/src/sync/mutex.go:162 +0x165
sync.(*Mutex).Lock(...)
	/opt/hostedtoolcache/go/1.18.6/x64/src/sync/mutex.go:81
sync.(*RWMutex).Lock(0x144644c6d00ca0ee?)
	/opt/hostedtoolcache/go/1.18.6/x64/src/sync/rwmutex.go:139 +0x36
github.com/kopia/kopia/repo/content.(*WriteManager).lock(...)
	/home/runner/work/kopia/kopia/repo/content/content_manager.go:927
github.com/kopia/kopia/repo/content.(*WriteManager).addToPackUnlocked(0xc006a229a0, {0x1ba41b8, 0xc0c88d3d10}, {{0xee, 0xa0, 0xc
[2023-08-30 13:01:49.229] [info]  , 0xd0, 0xc6, 0x44, 0x46, ...}, ...}, ...)
/home/runner/work/kopia/kopia/repo/content/content_manager.go:276 +0x225
github.com/kopia/kopia/repo/content.(*WriteManager).rewriteContent(0x2492fa0?, {0x1ba41b8, 0xc0c88d3d10}, {{0xee, 0xa0, 0xc, 0xd0, 0xc6, 0x44, 0x46, ...}, ...}, ...)
	/home/runner/work/kopia/kopia/repo/content/content_manager.go:724 +0x2dd
github.com/kopia/kopia/repo/content.(*WriteManager).RewriteContent(0xc006a229a0, {0x1ba41b8, 0xc0c88d3d10}, {{0xee, 0xa0, 0xc, 0xd0, 0xc6, 0x44, 0x46, ...}, ...})
	/home/runner/work/kopia/kopia/repo/content/content_manager.go:665 +0x232
github.com/kopia/kopia/repo/maintenance.RewriteContents.func1()
	/home/runner/work/kopia/kopia/repo/maintenance/content_rewrite.go:100 +0x6d0
created by github.com/kopia/kopia/repo/maintenance.RewriteContents
	/home/runner/work/kopia/kopia/repo/maintenance/content_rewrite.go:68 +0x1be
```
and a final
```
[2023-08-30 14:33:02.793] [error] failed to load
[2023-08-30 14:33:03.296] [info]  reloading
[2023-08-30 14:33:03.296] [error] failed to load
[2023-08-30 14:33:03.797] [info]  reloading
[2023-08-30 14:33:03.797] [error] failed to load
[2023-08-30 14:33:04.298] [info]  reloading
[2023-08-30 14:33:04.298] [error] failed to load
[2023-08-30 14:33:04.799] [info]  reloading
[2023-08-30 14:33:04.799] [error] failed to load
[2023-08-30 14:33:05.300] [info]  reloading
[2023-08-30 14:33:05.301] [error] failed to load
[2023-08-30 14:33:05.802] [info]  reloading
[2023-08-30 14:33:05.802] [error] failed to load
[2023-08-30 14:33:06.302] [info]  reloading
[2023-08-30 14:33:06.303] [error] failed to load
[2023-08-30 14:33:06.804] [info]  reloading
[2023-08-30 14:33:09.835] [info]  stopServer: server not started
[2023-08-30 14:33:15.559] [info]  actuating Server repository
[2023-08-30 14:33:15.561] [info]  stopServer: server not started
```

Nonetheless big fan of your software. :)

**Comment by dominikmayer** [comment] 2023-09-20 06:01
That's the end of `kopia-20230918-035744-2558-server-start.63.log` after the latest crash:

```
[…]
2023-09-19T18:08:33.231938Z DEBUG kopia/repo [STORAGE] ListBlobs	{"prefix":"xw","resultCount":1,"error":null,"duration":"2.463883959s"}
2023-09-19T18:08:33.251861Z DEBUG kopia/repo [STORAGE] ListBlobs	{"prefix":"xe","resultCount":2,"error":null,"duration":"2.483849291s"}
2023-09-19T18:08:47.965668Z DEBUG kopia/repo [STORAGE] ListBlobs	{"prefix":"xr","resultCount":20,"error":null,"duration":"17.197253917s"}
2023-09-19T18:09:44.897061Z DEBUG kopia/repo [STORAGE] ListBlobs	{"prefix":"xs","resultCount":112,"error":null,"duration":"1m14.128376959s"}
2023-09-19T18:09:48.425394Z DEBUG kopia/repo [STORAGE] ListBlobs	{"prefix":"xn76_","resultCount":0,"error":null,"duration":"3.522311917s"}
2023-09-19T18:09:50.889369Z DEBUG kopia/repo [STORAGE] ListBlobs	{"prefix":"xn75_","resultCount":3,"error":null,"duration":"5.986289167s"}
2023-09-19T18:10:00.898700Z DEBUG kopia/repo [STORAGE] ListBlobs	{"prefix":"xn74_","resultCount":41,"error":null,"duration":"15.995621416s"}
2023-09-19T18:10:37.823679Z DEBUG kopia/repo [STORAGE] GetBlob	{"blobID":"q86bb515be070f9b808cf5617558f64b6-s4598106dd10e75f1120","offset":0,"length":-1,"outputLength":20384930,"error":null,"duration":"36.868021542s"}
2023-09-19T18:10:37.877284Z DEBUG kopia/manifest performing automatic compaction of 16 contents
2023-09-19T18:10:37.877333Z DEBUG kopia/manifest compactLocked: contentIDs=16
2023-09-19T18:10:39.121522Z DEBUG kopia/repo [STORAGE] PutBlob	{"blobID":"q92c50244653d59299a6174b2759c8a9b-s75624a09162681a6120","length":31190,"error":null,"duration":"1.23342475s"}
```
And that's Kopia UI's `main.log`:

```
[…]
goroutine 29242193 [chan receive, 14 minutes]:
runtime.gopark(0x36?, 0x1050cbc08?, 0x18?, 0x5e?, 0x1053c1274?)
	/Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/proc.go:398 +0xc8 fp=0x14016039d70 sp=0x14016039d50 pc=0x104d588f8
runtime.chanrecv(0x14089e460c0, 0x14001225f28, 0x1)
	/Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/chan.go:583 +0x414 fp=0x14016039df0 sp=0x14016039d70 pc=0x104d24544
runtime.chanrecv2(0x1400b2cd6d0?, 0x10650ed08?)
	/Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/chan.go:447 +0x14 fp=0x14016039e20 sp=0x14016039df0 pc=0x104d24114
github.com/kopia/kopia/repo/maintenance.DeleteUnreferencedBlobs.func1()
	/Users/runner/work/kopia/kopia/repo/maintenance/blob_gc.go:45 +0x6c fp=0x14016039f60 sp=0x14016039e20 pc=0x1053c121c
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/Users/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x58 fp=0x14016039fd0 sp=0x14016039f60 pc=0x1050efdd8
runtime.goexit()
	/Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14016039fd0 sp=0x14016039fd0 pc=0x104d8d1c4
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 91
	/Users/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x98

[2023-09-20 01:10:39.236] [info]  child process exited with code 2 and signal null
[2023-09-20 12:48:14.498] [error] failed to load content
[2023-09-20 12:48:14.514] [info]  Checking for update
[2023-09-20 12:48:15.009] [info]  reloading
[…]
```

**Comment by jkowalski** [comment] 2023-09-23 18:16
@alindskog can you ping me on Slack, since you may have a repro for the GetDeleted() case, i'm interested in grabbing more details from you.

**Comment by jkowalski** [comment] 2023-09-25 03:14
Thanks @alindskog for your report, thanks to your stack trace I think I now understand the root cause of the issue and the fix is incoming.

This is essentially a race between index building and index refresh done by another goroutine. Because `content.Info` can be backed by memory-mapped indexes, when we close the mmap(), the memory contents become undefined.

This bug would only manifest itself in the UI/server mode when maintenance would run in parallel with other writes.

```
goroutine 2034 [running]:
runtime.throw({0x104d7c859?, 0xe68d?})
    /Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:1077 +0x40 fp=0x14006862730 sp=0x14006862700 pc=0x1040ddc20
runtime.sigpanic()
    /Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/signal_unix.go:875 +0x22c fp=0x14006862790 sp=0x14006862730 pc=0x1040f5a0c
github.com/kopia/kopia/repo/content/index.decodeBigEndianUint16(...)
    /Users/runner/work/kopia/kopia/repo/content/index/index_encode_util.go:20
github.com/kopia/kopia/repo/content/index.indexV2EntryInfo.GetPackBlobID({{0x282740022, 0x10, 0x51}, {{0x71, 0x71, 0x1, 0x3e, 0x13, 0x66, 0xb3, ...}, ...}, ...})
    /Users/runner/work/kopia/kopia/repo/content/index/index_v2.go:215 +0x48 fp=0x140068627c0 sp=0x140068627a0 pc=0x1044f98a8
github.com/kopia/kopia/repo/content/index.(*indexV2EntryInfo).GetPackBlobID(0x1d00014006862888?)
    <autogenerated>:1 +0x7c fp=0x14006862860 sp=0x140068627c0 pc=0x1044ff7fc
github.com/kopia/kopia/repo/content.(*deletedInfo).GetPackBlobID(0x10560b6c0?)
    <autogenerated>:1 +0x30 fp=0x14006862880 sp=0x14006862860 pc=0x104634ee0
github.com/kopia/kopia/repo/content/index.buildPackIDToIndexMap({0x1400684a6c0, 0x21, 0x140068629b8?})
    /Users/runner/work/kopia/kopia/repo/content/index/index_v2.go:460 +0x6c fp=0x140068628e0 sp=0x14006862880 pc=0x1044fa94c
github.com/kopia/kopia/repo/content/index.newIndexBuilderV2({0x1400684a6c0?, 0x21, 0x21})
    /Users/runner/work/kopia/kopia/repo/content/index/index_v2.go:510 +0xfc fp=0x14006862a30 sp=0x140068628e0 pc=0x1044fabfc
github.com/kopia/kopia/repo/content/index.Builder.buildV2(0x140038950b0, {0x1058854e0?, 0x1400b42dc40?})
    /Users/runner/work/kopia/kopia/repo/content/index/index_v2.go:558 +0x48 fp=0x14006862bc0 sp=0x14006862a30 pc=0x1044fb008
github.com/kopia/kopia/repo/content/index.Builder.BuildStable(0x0?, {0x1058854e0?, 0x1400b42dc40?}, 0x10442f29c?)
    /Users/runner/work/kopia/kopia/repo/content/index/index_builder.go:143 +0x34 fp=0x14006862c10 sp=0x14006862bc0 pc=0x1044f69b4
github.com/kopia/kopia/repo/content/index.Builder.BuildShards(0x140001b7f00?, 0x105896d08?, 0x1, 0x104d84815?)
    /Users/runner/work/kopia/kopia/repo/content/index/index_builder.go:210 +0x210 fp=0x14006862d80 sp=0x14006862c10 pc=0x1044f7110
github.com/kopia/kopia/repo/content.(*WriteManager).flushPackIndexesLocked(0x140029654a0, {0x105896db0?, 0x1400ae99490?}, {0x2, 0x1400000, 0x2, {0x1, 0x1176592e000, 0x7, 0xd18c2e28000, ...}})
    /Users/runner/work/kopia/kopia/repo/content/content_manager.go:454 +0x158 fp=0x14006863010 sp=0x14006862d80 pc=0x104628248
github.com/kopia/kopia/repo/content.(*WriteManager).Flush(0x140029654a0, {0x105896db0, 0x1400ae99490})
    /Users/runner/work/kopia/kopia/repo/content/content_manager.go:640 +0x42c fp=0x14006863200 sp=0x14006863010 pc=0x10462978c
github.com/kopia/kopia/repo/manifest.(*committedManifestManager).maybeCompactLocked(0x1400012d3b0, {0x105896db0, 0x1400ae99490})
    /Users/runner/work/kopia/kopia/repo/manifest/committed_manifest_manager.go:236 +0x138 fp=0x14006863280 sp=0x14006863200 pc=0x104637048
github.com/kopia/kopia/repo/manifest.(*committedManifestManager).loadCommittedContentsLocked(0x1400012d3b0, {0x105896db0?, 0x1400ae99490})
    /Users/runner/work/kopia/kopia/repo/manifest/committed_manifest_manager.go:183 +0x1e8 fp=0x14006863340 sp=0x14006863280 pc=0x104636788
github.com/kopia/kopia/repo/manifest.(*committedManifestManager).ensureInitializedLocked(0x1400012d3b0, {0x105896db0, 0x1400ae99490})
    /Users/runner/work/kopia/kopia/repo/manifest/committed_manifest_manager.go:311 +0x12c fp=0x140068633e0 sp=0x14006863340 pc=0x10463784c
github.com/kopia/kopia/repo/manifest.(*committedManifestManager).findCommittedEntries(0x1400012d3b0, {0x105896db0?, 0x1400ae99490?}, 0x1040e8ee8?)
    /Users/runner/work/kopia/kopia/repo/manifest/committed_manifest_manager.go:75 +0xe8 fp=0x14006863550 sp=0x140068633e0 pc=0x104635b48
github.com/kopia/kopia/repo/manifest.(*Manager).Find(0x140038951a0, {0x105896db0?, 0x1400ae99490?}, 0x140181b3560?)
    /Users/runner/work/kopia/kopia/repo/manifest/manifest_manager.go:162 +0x50 fp=0x140068638a0 sp=0x14006863550 pc=0x104639050
github.com/kopia/kopia/repo.(*directRepository).FindManifests(0x105607b80?, {0x105896db0?, 0x1400ae99490?}, 0x4?)
    /Users/runner/work/kopia/kopia/repo/repository.go:224 +0x28 fp=0x140068638d0 sp=0x140068638a0 pc=0x104740b28
github.com/kopia/kopia/snapshot/policy.GetPolicyHierarchy({0x105896db0, 0x1400ae99490}, {0x130804230, 0x14002965600}, {{0x140039fbf60, 0x9}, {0x140039fbfa4, 0x4}, {0x140039fbf80, 0xd}}, ...)
    /Users/runner/work/kopia/kopia/snapshot/policy/policy_manager.go:69 +0x5d0 fp=0x14006863be0 sp=0x140068638d0 pc=0x1047626a0
github.com/kopia/kopia/snapshot/policy.GetEffectivePolicyWithOverride({0x105896db0?, 0x1400ae99490?}, {0x130804230?, 0x14002965600?}, {{0x140039fbf60, 0x9}, {0x140039fbfa4, 0x4}, {0x140039fbf80, 0xd}}, ...)
    /Users/runner/work/kopia/kopia/snapshot/policy/policy_manager.go:53 +0x4c fp=0x14006863c60 sp=0x14006863be0 pc=0x104761fdc
github.com/kopia/kopia/snapshot/policy.GetEffectivePolicy({0x105896db0?, 0x1400ae99490?}, {0x130804230?, 0x14002965600?}, {{0x140039fbf60, 0x9}, {0x140039fbfa4, 0x4}, {0x140039fbf80, 0xd}})
    /Users/runner/work/kopia/kopia/snapshot/policy/policy_manager.go:46 +0x50 fp=0x14006863cd0 sp=0x14006863c60 pc=0x104761f20
github.com/kopia/kopia/internal/server.(*sourceManager).refreshStatus(0x14000321ce0, {0x105896c60?, 0x14006c3d1a0?})
    /Users/runner/work/kopia/kopia/internal/server/source_manager.go:416 +0xc0 fp=0x14006863e10 sp=0x14006863cd0 pc=0x104893180
github.com/kopia/kopia/internal/server.(*sourceManager).runLocal(0x14000321ce0, {0x105896c60, 0x14006c3d1a0})
    /Users/runner/work/kopia/kopia/internal/server/source_manager.go:202 +0x280 fp=0x14006863f10 sp=0x14006863e10 pc=0x104891a40
github.com/kopia/kopia/internal/server.(*sourceManager).run(0x14000321ce0, {0x105896d08?, 0x140005ee120?}, 0x1)
    /Users/runner/work/kopia/kopia/internal/server/source_manager.go:171 +0x110 fp=0x14006863fa0 sp=0x14006863f10 pc=0x104891650
github.com/kopia/kopia/internal/server.(*sourceManager).start.func1()
    /Users/runner/work/kopia/kopia/internal/server/source_manager.go:157 +0x34 fp=0x14006863fd0 sp=0x14006863fa0 pc=0x104891504
runtime.goexit()
    /Users/runner/hostedtoolcache/go/1.21.1/x64/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14006863fd0 sp=0x14006863fd0 pc=0x1041151c4
created by github.com/kopia/kopia/internal/server.(*sourceManager).start in goroutine 480
```

**Comment by jkowalski** [comment] 2023-09-26 02:16
There's a potential fix available to try out in #3356. To build kopia ui locally you simply need `make kopia-ui`.

**Comment by probablykasper** [comment] 2023-09-28 10:05
Hard to know for sure if it's fixed since the reproduction is unreliable, so I'll suggest we assume it's fixed and close the issue, then reopen if proven otherwise

**Comment by julio-lopez** [comment] 2023-09-28 22:57
Once we review and merge the PR

**Closed** 2024-01-21 19:51 UTC
Labels: bug, ux, keep-open
