### ISSUE TITLE
Extremely high memory usage when backing up a large number of small files to a local repository

### ISSUE THREAD

**Issue by oenhu** [kopia/kopia#3642] opened 2024-02-09 16:18 UTC
![kopia](https://github.com/kopia/kopia/assets/24935784/c934bc86-1547-4934-b859-3d22b72c00a6)
![kopia2](https://github.com/kopia/kopia/assets/24935784/2ccbcecc-43ec-4a0d-9ce6-39b1c001c158)

Extremely high memory usage when backing up a large number of small files to a local repository
The local repository is set up as shown above
The majority of the small files are large image caches generated by the chat program WeChat and temporary files of various software under Windows AppData.
All snapshots have compression turned on, the algorithm is zstd-better-compression
Currently observed up to 150G memory footprint (512G for Server),

**Comment by lupusA** [comment] 2024-02-09 16:29
Hi, 

this should be duplicate of #3539. I will close this one for the sake of clarity.

**Closed** 2024-02-09 16:30 UTC
Labels: duplicate
