### ISSUE TITLE
Maintenance not running correctly automatically

### ISSUE THREAD

**Issue by RavenMacDaddy** [kopia/kopia#1439] opened 2021-10-23 08:07 UTC
This is a continuation of issue #1408.

---

![image](https://user-images.githubusercontent.com/67732686/138546679-0694f90c-b975-498f-9bd8-d57f21193102.png)

I checked the maintenance info, and it says indeed that it's scheduled to run every hour for quick and every day for full.

Note however that I'm almost exclusively using the UI - could that interfere or result in maintenance not being run automatically?

I also read somewhere that KopiaUI includes the CLI, but I was never able to use it unless explicitly installed through Scoop - so CLI and KopiaUI are installed separately, in case that could have any effect.

![image](https://user-images.githubusercontent.com/67732686/138546741-bd412bfe-0ed6-4b08-99c6-963d8e194c7b.png)

![image](https://user-images.githubusercontent.com/67732686/138546764-74041cb7-f2ed-4d94-b354-d959542703fe.png)

As can be seen in these images, the example mentioned in this issue hasn't changed, and I've tried running maintenance at different times manually to see if that could make a difference - so far it hasn't.

---

![image](https://user-images.githubusercontent.com/67732686/138547309-880e31da-cac3-4f36-be12-b45415d80a7a.png)

Here we go, I'd to connect to the repository in question and manually run it, so for some reason maintenance is not being run correctly automatically. 

Here is the maintenance info when being run from that dir.

![image](https://user-images.githubusercontent.com/67732686/138547353-2ea8c6fa-ba39-4e98-a522-22ebe22c6e35.png)

---

Weirdly enough, I wasn't connected to a repository when running the maintenance command the first time - unless Kopia stays connected to the last repository even between reboots and the like.

However to be fair, I might have connected to a repository in a previously closed PowerShell window, in case that's something Kopia keeps loaded, not sure.

Whatever the case, here's what was returned the first time I ran maintenance in my current PS window:

![image](https://user-images.githubusercontent.com/67732686/138548280-34177b30-ab00-4d7d-a37d-6aaa6f99a4f8.png)

... and here's the second time: 

![image](https://user-images.githubusercontent.com/67732686/138548295-f24a7df3-74d3-4b36-9735-c81610b7ae8a.png)

Note that so far, I haven't explicitly connected to a repository or changed the current dir; still C:\Windows\System32, however the data from those two are different, and they're both running full maintenance (also not specified as you can see).

**Comment by santacruzskim** [comment] 2021-11-04 21:04
I'm not sure how or why, but maintenance is now running a check every 10 minutes and appearing in the UI task list.

I upgraded to 0.9.4, but had confirmed the issue had persisted well after that. I also did a reboot at some point in the last few days, but no changes to the machine or Kopia have been made and I rebooted plenty during testing leading up to this.  Scratching my head, but happy it's working.

To be specific, I have the defaults set (24h full, 1h quick) and every 10 minutes it appears to be checking on maintenance status and listing when the next quick and full maintenance tasks are scheduled.  Then when it hits those times it actually runs! In the CLI `kopia maintenance info` properly displays the information as well.  All tasks in the UI are listed in the description as "Periodic maintenance" regardless of what it ends up doing (check vs quick vs full).

<details>
  <summary>Example of Maintenance Check:</summary>
Runs Maintenance Check Every 10 Min

<html>
<body>


13:50:16.835 | reloading committed manifest contents: rev=514 last=0
-- | --
13:50:16.835 | listing manifest contents
13:50:16.835 | updating timestamp on C:\Users\santa\AppData\Local\kopia\95c8e47cc32494ca\metadata/qe/fc953ea93831a3ac136853df45da87e-s03d202930f59f8bb109.f to 2021-11-04 13:50:16.8359741 -0700 PDT
13:50:16.835 | updating timestamp on C:\Users\santa\AppData\Local\kopia\95c8e47cc32494ca\metadata/qa/b78d7e621f0685c9b551197c9fa8c39-sc4c55553d19b3f5d109.f to 2021-11-04 13:50:16.8359741 -0700 PDT
13:50:16.835 | updating timestamp on C:\Users\santa\AppData\Local\kopia\95c8e47cc32494ca\metadata/q0/7f9462548c0029875b941b4741f7ab8-s1813e1438e850a05109.f to 2021-11-04 13:50:16.8359741 -0700 PDT
13:50:16.835 | updating timestamp on C:\Users\santa\AppData\Local\kopia\95c8e47cc32494ca\metadata/qb/428acaf78a407e3e1bc74957aee6e7b-s702d09c409784400109.f to 2021-11-04 13:50:16.8359741 -0700 PDT
13:50:16.835 | updating timestamp on C:\Users\santa\AppData\Local\kopia\95c8e47cc32494ca\metadata/qb/40696698edddd7fa1e9908fd98d6cbd-s4dc2c99c4830be50109.f to 2021-11-04 13:50:16.8359741 -0700 PDT
13:50:16.836 | updating timestamp on C:\Users\santa\AppData\Local\kopia\95c8e47cc32494ca\metadata/q6/2bb91170e84805e6a24909e3d9e5216-s54997f58ecc82edd109.f to 2021-11-04 13:50:16.8369098 -0700 PDT
13:50:16.836 | updating timestamp on C:\Users\santa\AppData\Local\kopia\95c8e47cc32494ca\metadata/q8/45ada3129d80757504608a772e36dfe-sf0ccb593e3cccf89109.f to 2021-11-04 13:50:16.8369098 -0700 PDT
13:50:16.836 | updating timestamp on C:\Users\santa\AppData\Local\kopia\95c8e47cc32494ca\metadata/qb/3b28ebb7c46641f29990ef1a47f6281-sffee729657671b05109.f to 2021-11-04 13:50:16.8369098 -0700 PDT
13:50:16.836 | updating timestamp on C:\Users\santa\AppData\Local\kopia\95c8e47cc32494ca\metadata/q2/f7e411fa1154bf2f2551ca2c9a006bf-s2b7c1354e950b0b8109.f to 2021-11-04 13:50:16.8369098 -0700 PDT
13:50:16.837 | updating timestamp on C:\Users\santa\AppData\Local\kopia\95c8e47cc32494ca\metadata/q7/83f62c57279fc8f380fdce51a5a8454-s3f85fc6930549459109.f to 2021-11-04 13:50:16.8379082 -0700 PDT
13:50:16.846 | not due for full maintenance cycle until 2021-11-05 09:19:36.6950366 -0700 PDT
13:50:16.846 | not due for quick maintenance cycle until 2021-11-04 14:20:16.2956859 -0700 PDT
13:50:16.846 | not due for maintenance


</details>

<details>
  <summary>Example of Maintenance Run:</summary>
  Runs Quick Maintenance Every 60 Min
<html>
<body>


12:20:15.224 | reloading committed manifest contents: rev=501 last=0
-- | --
12:20:15.224 | listing manifest contents
12:20:15.226 | updating timestamp on C:\Users\santa\AppData\Local\kopia\95c8e47cc32494ca\metadata/q2/f7e411fa1154bf2f2551ca2c9a006bf-s2b7c1354e950b0b8109.f to 2021-11-04 12:20:15.2261449 -0700 PDT
12:20:15.232 | not due for full maintenance cycle until 2021-11-05 09:19:36.6950366 -0700 PDT
12:20:15.232 | due for quick maintenance cycle
12:20:15.233 | scheduling next quick cycle at 2021-11-04 12:20:14.5348259 -0700 PDT
12:20:15.248 | Acquiring maintenance lock in file C:\Users\santa\AppData\Roaming\kopia\repository.config.mlock
12:20:15.248 | Running quick maintenance...
12:20:15.646 | quick maintenance not required for epoch manager
12:20:15.646 | Finished quick maintenance.


</body>
</html>
</details>

Not sure where you got with this, @zyradyl , but for the time being all seems well on my setup.

**Comment by zyradyl** [comment] 2021-11-04 21:40
darn it. this mirrors my experience as well. 

while trying to debug on this past weekend, the only time i was able to consistently  reproduce the issue was to create a new repository in the UI and then never restart the UI. restarting fixed the issue, running manual maintenance fixed the issue, etc. i inserted logging as well and was never able to recreate the issue with the new log points. i was hoping to come back to it this weekend and maybe find something less frustrating to report, but you just confirmed my experience.

@ravenmacdaddy, can you try running manual maintenance on each config file with the 'kopia --config-file=<path> maintenance run --full' command and then restart your UI and see if it corrects the issue?

right now it seems like this is an odd one off error. even the logging that i though was confused is actually completely fine due to the file name being formed from the thread ID.

sorry i don't have a better answer :(

-z

**Comment by xxxliqu1dxxx** [comment] 2021-11-05 00:24
> I'm not sure how or why, but maintenance is now running a check every 10 minutes and appearing in the UI task list.

Same here. 
![image](https://user-images.githubusercontent.com/83290244/140438172-cd8734e8-4080-4534-9960-e49d556065a5.png)

![image](https://user-images.githubusercontent.com/83290244/140438190-9d4beb32-0c41-4380-91c7-e8955d2ea1b2.png)

Not sure why it's checking every 10 mins to then realize quick maintenance is not enabled.

**Comment by zyradyl** [comment] 2021-11-05 00:27
@xxxliqu1dxxx the periodic maintenance is the servers way of checking when it is time to run maintenance. it's a goroutine that is launched at the same time as the main server thread for the repository is started, similar to cache updates. if it is time, then the goroutine fires the actual maintenance task.

**Comment by xxxliqu1dxxx** [comment] 2021-11-05 00:29
Is this normal for it to execute every 10 minutes? And is this what could
cause the number of API calls to be high as per the other issue documented?
That 10 min interval seems excessive...  no?

**Comment by zyradyl** [comment] 2021-11-05 00:35
@xxxliqu1dxxx it is normal yes. it is unrelated to the B2 API calls in the other issue, that is likely from the refreshPeriodically goroutine. the way forward on B2 i think would be something like only calling refreshes before each action, or when manually refreshed.

**Comment by santacruzskim** [comment] 2021-11-05 05:26
I don't fully understand why a process needs to run every 10 minutes to check on the status of something that runs on a schedule, but I also edit video for a living so what do I know?! :)   Regardless, it's nice to have this situation corroborated with other users' stories to stop me from going down that next troubleshooting rabbit hole, re: 10 min interval maintenance checks!  It is annoying to have it clutter up the logs though, and considering the UI only shows the last 100 tasks which is only like 5 hours of history with all these maintenance checkups and my other snapshot tasks.

**Comment by xxxliqu1dxxx** [comment] 2021-11-05 17:24
> I don't fully understand why a process needs to run every 10 minutes to check on the status of something that runs on a schedule,

I am also agreeing with the above.... I am confused as well. Does this mean my HDD are spinning up just do that check and basically do nothing as it's scheduled and not yet the time? And if I had a repo in the cloud, is this doing API calls every 10 mins? If so, i think this should be configurable and have the maintenance done when a snapshot is done. 

I would argue that slower snapshots for the sake of keeping hdds spun down, or API calls to lower frequency vs the unnecessary 10 mins checks, since there's nothing to do until it's scheduled is worth it. Is this something that could get configured?

**Comment by zyradyl** [comment] 2021-11-05 18:31
you would have to follow up with Jarek to be completely sure but my guess would be the check is there in the event the server is asleep past the actual maintenance time or if the maintenance owner has been changed/time manually changed from the cli. for the first, if maintenance is to be run at 6am but the computer is asleep until 6:05 this would run maintenance at 6:15 at the latest, versus having to wait for another cycle and hoping the computer is awake.

the only call that is made, without the code in front of me, is to grab the kopia.maintenance file and check. it's possible not even that is checked if it is cached locally.

the API calls and drive spinups would occur far more frequently from the cache refreshes that occur every 5 minutes than the maintenance checks. the cache refreshes occur to make sure any policy changes made on a different system are picked up by your client before a snapshot is called.

most of this is here because kopia was designed so multiple computers use one repository, and each of those computers may be able to change policies, upload new files, etc. additionally,maintenance owner could change at any time. the cache refresh keeps things updated and the every 10 minutes maintenance check is there if the owner changes or the maintenance time passed and somehow the UI missed it.

**Comment by RavenMacDaddy** [comment] 2021-11-06 08:37
For me it's very hard to say.

When I check the individual logs with kopia --config-file=<path> maintenance info, everything looks normal, yet when I run manual full maintenance, what's referenced is: Found safe time to drop indexes: 2021-11-04 09:01:08.3165877 +0100 CET

... but if I look at all the different types of maintenance, what's referenced from that date was ran at 2021-11-04 10:01:18 CET - though this might be me being completely ignorant.

Whatever the case may be, it's still worth noting that a consistent pattern you've noticed yourself is maintenance not working, at least when a new repository is created through the UI and the UI itself is never restarted through any means.

Since it's been a while since starting this issue, I can't remember if I did restart the UI or not somehow while reporting that maintenance wasn't working, but has any development been done in the software during that time that may have produced the improved results that you're experiencing?

**Closed** 2021-11-07 00:10 UTC

**Comment by zyradyl** [comment] 2021-11-07 00:56
@santacruzskim @RavenMacDaddy @xxxliqu1dxxx 

Jarek managed to find the issue, on creating a new repo the context was carrying the cancelation signal over, which meant the goroutine was killed before it could be fired. there's also some nice QOL fixes here, including moving the maintenance timer to every 4 hours or next scheduled time, whichever is sooner, or 30 minutes later if an error is thrown.

bonus: when the 4 hour timer expires, if it still isn't time for maintenance there isn't a Tasks entry added in the UI, so it should cut down on clutter.

i did a manual test with maintenance set to run every minute and everything looks fine on my end, even on new fs created repos.

v0.9.5 should be released some time tomorrow, including this fix

this one was sneaky and a bit beyond me but thanks for all the reporting, screenshots, etc, and patience! feel free to reopen if it keeps happening. :)

**Comment by RavenMacDaddy** [comment] 2021-11-07 06:28
Awesome, glad we're making this project even better as a team.

**Comment by xxxliqu1dxxx** [comment] 2021-11-07 11:43
Awesome! Thank you again for all the hard work. This is a great project.
