### ISSUE TITLE
Can't create snapshot action 0.13.0

### ISSUE THREAD

**Issue by YFrendo** [kopia/kopia#3046] opened 2023-05-26 21:19 UTC
I'm using kopiaGUI and since the last update 0.13.0 when I create a NEW folder snapshot directory I can't assign a snapshot action to this snapshot.

Everything else seems to work perfectly but when I type some path to my shell it's not save in the policy. 

<img width="1673" alt="Capture d’écran 2023-05-26 à 23 17 24" src="https://github.com/kopia/kopia/assets/66957426/bc5f3d68-b2b4-4d11-893a-d914d5e86dfb">

As you can see it's not filed inside the effective field.

If someone know who to fox this!

I'm on Ubuntu Server, kopia run with an apt install on server UI

**Comment by YFrendo** [comment] 2023-05-27 08:14
With some investigation I have notice that the internal representation only modify the script key and not the path one in the internal representation.
With a new one they are not created either


JSON Representation
This is the internal representation of a policy

{
    "retention": {},
    "files": {},
    "errorHandling": {},
    "scheduling": {
        "intervalSeconds": 10800
    },
    "compression": {},
    "actions": {
        "beforeSnapshotRoot": {
            "path": "/path/not/modify",
            "script": "/path/modify",
            "timeout": 300
        },
        "afterSnapshotRoot": {
            "path": "/path/not/modify",
            "script": "/path/modify",
            "timeout": 300
        }
    },
    "logging": {
        "directories": {},
        "entries": {}
    },
    "upload": {}
}

**Comment by stenki-eu** [comment] 2023-06-28 15:13
> I have the same issue. Whatever I enter as command is neither reflected in the "Effective" column nor saved in the policy.

I have the same problem. The entered information is not saved.

**Comment by lupusA** [comment] 2023-07-09 07:12
I think i found the issue.

**Comment by tribor** [comment] 2023-07-10 12:04
if I edit the policy via CLI the UI still does not represent my changes. I wonder if "path" or "script" is the correct value?
```
    "actions": {
        "afterSnapshotRoot": {
            "path": "/jobs/success-alifaces-daily.sh",
            "timeout": 60
        }
    },
```

**Comment by lupusA** [comment] 2023-07-10 12:35
Hi @tribor, 

the UI in version 0.13 looks for "script". After merging the PR https://github.com/kopia/htmlui/pull/163 it will work again, so that actions can be added again. I've tested it myself. 

With the PR, actions are saved and correctly filled when open the policy editor again. In version 0.12.X it is working as intended. The change that broke it was merged in May.

**Closed** 2023-07-14 03:07 UTC
