### ISSUE TITLE
Snapshot finished uploading but displays as size 0 B 

### ISSUE THREAD

**Issue by eurodrew555** [kopia/kopia#2382] opened 2022-09-08 13:36 UTC
I create a new snapshot using manual snapshot only.
The cli-logs logs "finished uploading" but the size on the top level Snapshots page displays as 0 B.

This was a large snapshot of 875.1 GB.

When I go into the snapshot on the Snapshots page it shows as:

![snapshots](https://user-images.githubusercontent.com/13842996/189134481-9f35fb61-03f7-45bd-b291-d74f286a7ad5.png)

Also attached are the cli-logs from creating the snapshot until it finished.
content-logs does not have any log entries for the same time period.

[cli-logs.txt](https://github.com/kopia/kopia/files/9527194/cli-logs.txt)

If I take another manual snapshot it completes in 1 min 17 secs, but this time now correctly shows the size as 875.1 GB
This is the same size and number of files/dirs as the first snapshot that was taken (which is expected, no data has changed since the first snapshot was taken).

![snapshots - second run](https://user-images.githubusercontent.com/13842996/189136370-77d3cfa0-1534-4dd3-896b-3c0e5f1b6813.png)

The repository is a MinIO S3 bucket.

Will also add that this seems to happen only on large snapshots.
I cannot reproduce with small snapshots.

**Comment by s-h-a-r-d** [comment] 2022-09-10 19:02
Same thing happened to me with 500GB+ snapshot. Just manually triggered another snapshot and that got rid of the `incomplete` ones and then correct size was shown in UI.

I figured it is intended behavior because I was seeing the `incomplete` tags = snapshot is not complete = 0B shown in UI.

**Comment by lupusA** [comment] 2023-03-24 07:19
Hey, 

when snapshotting large directories, kopia might mark parts of the snapshot as "incomplete". The reason is, that kopia establish a connection for a maximum of 45 minutes. Once kopia is able to snapshot the directory in 45 minutes or less, these incomplete marked snapshots will be removed. 

Cheers,

**Comment by ntolia** [comment] 2023-03-27 17:02
I'm closing this one out as this was reported on Slack as having been addressed by @lupusA. Please feel free to ping me or reopen if there is still an open question.

**Closed by ntolia** 2023-03-27 17:02 UTC
