### ISSUE TITLE
Backend enhancement - rclone

### ISSUE THREAD

**Issue by kellytrinh** [kopia/kopia#497] opened 2020-07-23 13:09 UTC
As a potential suggestion for feature development - consider mimicking the restic approach to backend support by leveraging rclone --- can help boost number of backends easily without dealing with all the odd API issues of each provider.

**Comment by hickinbottoms** [comment] 2020-07-23 13:22
Think this is a duplicate of #313 .

**Comment by julio-lopez** [comment] 2020-08-04 20:05
Closing as duplicate of #313

**Closed by julio-lopez** 2020-08-04 20:05 UTC
Labels: duplicate
