### ISSUE TITLE
Kopia shows Zero bytes for the snapshot size if the latest snapshot is incomplete

### ISSUE THREAD

**Issue by Ember-ruby** [kopia/kopia#2681] opened 2023-01-05 14:42 UTC
![Screenshot from 2023-01-06 01-41-32](https://user-images.githubusercontent.com/48266942/210806076-7f662285-7905-4b58-9e7b-9dc715397de7.png)
![Screenshot from 2023-01-06 01-41-44](https://user-images.githubusercontent.com/48266942/210806084-252cabf6-2fb4-4761-bb07-5c6a4048a235.png)

**Comment by xxxliqu1dxxx** [comment] 2023-01-11 19:55
I believe that's by design. Snapshot is not committed so it cannot know the size. Just snapshotting again and letting it finish would fix this.

**Comment by lupusA** [comment] 2023-03-28 05:22
I will update the FAQ to make it clearer. Questions about incomplete Snapshots have been raised in the forum as well. 

Cheers,

**Closed** 2023-03-30 00:35 UTC
