### ISSUE TITLE
Kopia Server casues unnecessary repo storage activity

### ISSUE THREAD

**Issue by auanasgheps** [kopia/kopia#3416] opened 2023-10-29 23:39 UTC
Hello,

I have installed Kopia Server via Docker on my NAS (the setup is a painful process, but it's another story). 

Kopia Server reads repository files very often, even if there are no backups running. This causes, in my opinion, unnecessary reads and my HDDs spin up constantly because of this service. If I turn off Kopia Server container, my HDDs do not spin up for very long time.

I have run fatrace for few hours and noticed that reads usually happen every 1 hour, but sometimes every 20 or 40 minutes.

During this period, Kopia Server was the only service reading and writing to my HDDs and the Kopia Client (there's only one) was disconnected.

If this is not a bug and you consider this a feature, please let it be user customizable. 

As of now, Kopia Server is not suitable for people who use HDD spindown.

I am usign the latest version 0.15, but 0.14.1 had the same issue as well.

**Comment by mvosz** [comment] 2023-11-01 10:02
same here

**Comment by lupusA** [comment] 2023-11-01 18:19
Hi, 

i have to check, but we had this already in the past. If I remember correctly, it was that the clients checks for new policies and updates - therefore causing activity on the server side. It is not a bug and more or less a design decision. 

This is what has been stated some time ago:

> Kopia performs periodic refresh of the repository indices to discover new policies and bring in additional contents to aid in deduplication. The timing of this refresh has not been really tuned and is probably too aggressive and we can/should change it.

The issue here is maybe related to https://github.com/kopia/kopia/issues/2759 

I guess this is the reason that the HDDs are spinning up again from time to time. 

Cheers,

**Comment by lupusA** [comment] 2023-11-02 06:22
Closing in favor of #2921. 

Cheers,

**Closed by lupusA** 2023-11-02 06:22 UTC
Labels: enhancement, needs-repro, resource-utilization

**Comment by auanasgheps** [comment] 2023-11-02 10:03
Hi, thanks for your updates. If you need anything let me know. I can always reproduce the issue and I tracked it using fatrace.
