### ISSUE TITLE
Creating snapshot fails due to EPERM, even with ignoreDirectoryErrors=true ignoreFileErrors=true

### ISSUE THREAD

**Issue by strager** [kopia/kopia#1599] opened 2021-12-18 06:27 UTC
I have a directory called `pkg` with broken file permissions (`0111`):
```
$ ls -la ~/Projects/quicklint-js/dist/arch/
total 48
drwxrwxr-x 3 strager strager 4096 Dec 17 21:55 .
drwxrwxr-x 8 strager strager 4096 Dec 13 19:33 ..
-rw-rw-r-- 1 strager strager 1236 Dec  6 16:04 Dockerfile
-rw-rw-r-- 1 strager strager   97 Dec  9 17:24 .gitignore
-rwxrwxr-x 1 strager strager 1428 Nov  9 19:54 lint.sh
d--x--x--x 2 strager strager 4096 Nov 26 00:50 pkg
-rw-rw-r-- 1 strager strager 1888 Dec 13 19:33 PKGBUILD-dev
-rw-rw-r-- 1 strager strager 1913 Dec 13 19:33 PKGBUILD-git
-rw-rw-r-- 1 strager strager 2148 Dec 13 19:33 PKGBUILD-release
-rw-rw-r-- 1 strager strager 3014 Dec  6 16:04 quick-lint-js.gpg.key
-rw-rw-r-- 1 strager strager 1435 Dec  6 16:04 README.md
-rwxrwxr-x 1 strager strager 2317 Dec 13 21:18 update-aur.sh
```

Backing up the directory fails:
```
$ kopia snapshot create --fail-fast ~/Projects/quicklint-js/dist/
Snapshotting strager@strapurp:/home/strager/Projects/quicklint-js/dist ...

 ! Error when processing "arch/pkg": permission denied
 * 0 hashing, 0 hashed (0 B), 0 cached (0 B), uploaded 4.6 KB (1 fatal errors), estimating...
Created partial snapshot with root kdd634a7a8e2f350b62a715fed77a82c7 and ID 28970403c4d50bfa7f42d0143ce6e65c in 0s
ERROR Found 1 fatal error(s) while snapshotting strager@strapurp:/home/strager/Projects/quicklint-js/dist.
```

The snapshot is basically empty according to `kopia mount`:
```
$ ls -lR /tmp/kopia-mount2141240165/strager@strapurp/home_strager_Projects_quicklint-js_dist/
/tmp/kopia-mount2141240165/strager@strapurp/home_strager_Projects_quicklint-js_dist/:
total 0
dr-xr-xr-x 1 root root 0 Dec 17 21:55 20211217-220832 (canceled)
dr-xr-xr-x 1 root root 0 Dec 17 21:55 20211217-220957 (canceled)

/tmp/kopia-mount2141240165/strager@strapurp/home_strager_Projects_quicklint-js_dist/20211217-220832 (canceled):
total 0
drwxrwxr-x 1 strager strager 0 Dec 17 21:55 arch

/tmp/kopia-mount2141240165/strager@strapurp/home_strager_Projects_quicklint-js_dist/20211217-220832 (canceled)/arch:
total 0

/tmp/kopia-mount2141240165/strager@strapurp/home_strager_Projects_quicklint-js_dist/20211217-220957 (canceled):
total 0
drwxrwxr-x 1 strager strager 0 Dec 17 21:55 arch

/tmp/kopia-mount2141240165/strager@strapurp/home_strager_Projects_quicklint-js_dist/20211217-220957 (canceled)/arch:
total 0
```

This happens despite my policy specifying that file and directory errors should be ignored:
```$ kopia policy get strapurp/ 
Policy for strager@strapurp:/home/strager/backups/strapurp:

[snip]

Files policy:
  Ignore cache directories:        true       (defined for this target)
  No ignore rules.
  Read ignore rules from files:               (defined for this target)
    .kopiaignore                  
  Scan one filesystem only:        true       (defined for this target)

Error handling policy:
  Ignore file read errors:        true       (defined for this target)
  Ignore directory read errors:   true       (defined for this target)
  Ignore unknown types:           true       inherited from (global)

Scheduling policy:
  Scheduled snapshots:
    None
  Manual snapshot:           false   inherited from (global)

Compression:
  Compressor: "zstd" (defined for this target)
  Compress files regardless of extensions.
  Compress files of all sizes.

[snip]
```

Without `--fail-fast`, backing up mostly works as expected. All the files (except `pkg` and everything inside) appear in the mounted snapshot. However, Kopia still reports the directory permission error as "fatal", despite the policy specifying that errors should be ignored. The `kopia snapshot create` command exits with status code `1`. I expect status code `0`.

OS: Linux Mint
Kopia version: 0.9.7

Two suggestions:

1. When `--fail-fast` is used, and a failure occurs, mention something like "stopping on the first error due to `--fail-fast`; snapshot might be incomplete"
2. When a permission-denied error occurs while reading a directory, and the `ignoreDirectoryErrors` setting is `true`, report the error but don't treat it as fatal (regardless of `--fast-fail`).

**Comment by jkowalski** [comment] 2021-12-27 17:56
So from what you're describing you have a policy on `strager@strapurp:/home/strager/backups/strapurp` that explicitly ignores directory errors (this is indicated by `defined for this target`)

That policy does not apply to `~/Projects/quicklint-js`.

**Comment by jkowalski** [comment] 2021-12-27 22:06
can you do `kopia policy show ~/Projects/quicklint-js`

**Comment by jkowalski** [comment] 2022-03-09 06:37
closing, please reopen if the issue is still there.

**Closed by jkowalski** 2022-03-09 06:37 UTC
Labels: waiting for response
