### ISSUE TITLE
Are there any plans to support VSS on windows?

### ISSUE THREAD

**Issue by Hoffenbar** [kopia/kopia#826] opened 2021-02-09 23:57 UTC
I noticed that it is not possible to backup files which are permanently locked. As a workaround I add a policy to ignore files and dirs which cannot be processed, but using VSS would probably a better way.

**Comment by jkowalski** [comment] 2021-02-10 02:21
Next version of Kopia will have support for Actions, which allows you to plug in scripts that run before/after a directory is snapshotted. I'm not super familiar with VSS but that in principle would be the right opportunity to capture a file for snapshot.

There's no documentation on kopia.io yet, but take a look at https://kopia.discourse.group/t/design-additional-features-for-snapshot-creation/197/3 for more information about this feature.

**Comment by jkowalski** [comment] 2021-02-10 02:21
Next version of Kopia will have support for Actions, which allows you to plug in scripts that run before/after a directory is snapshotted. I'm not super familiar with VSS but that in principle would be the right opportunity to capture a file for snapshot. 

See https://kopia.discourse.group/t/design-additional-features-for-snapshot-creation/197/3 for more information about this feature.

**Comment by jkowalski** [comment] 2021-02-10 02:22
(btw this code is now available in `master` branch and nightly builds - sadly there's no automated nightly channel for Windows yet)

**Comment by Hoffenbar** [comment] 2021-02-10 08:15
Thank you for responding, Ok, then maybe some external tool could be integrated like the ones mentioned here:
https://www.raymond.cc/blog/copy-locked-file-in-use-with-hobocopy/

**Comment by julio-lopez** [comment] 2021-03-07 07:33
Closing as a duplicate of #470

**Closed by julio-lopez** 2021-03-07 07:33 UTC
