### ISSUE TITLE
kopia-ui doesn't start after update to 18.1

### ISSUE THREAD

**Issue by fcalvet** [kopia/kopia#4261] opened 2024-11-18 10:38 UTC
Started from working version 17.0 on Kubuntu 22.10

Performed update to 18.1 from right click menu, kopia-ui didn't start anymore after.

Tried re-install using `sudo apt-get remove kopia-ui` & `sudo apt-get install kopia-ui`, kopia-ui still didn't start.

Gives out following error `[1868332:1118/112604.046805:FATAL:setuid_sandbox_host.cc(163)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/KopiaUI/chrome-sandbox is owned by root and has mode 4755.`

**Comment by basldfalksjdf** [comment] 2024-11-18 14:12
Could this be related to https://github.com/kopia/kopia/issues/4262?

**Comment by BryanWall** [comment] 2024-11-18 18:17
Happening on Macos also

**Comment by BryanWall** [comment] 2024-11-18 18:21
The Macos 18.1 client is stuck on initializing. Log says:

> unable to check for updates: unable to open update state file: open /Users/<username>/Library/Application Support/kopia/repository.config.update-info.json: no such file or directory

**Comment by BryanWall** [comment] 2024-11-18 18:25
The Macos 18.1 client is stuck initializing.

> 13:22:31.361 failed to open repository: unable to establish session for purpose=: error establishing session: unable to initialize session: rpc error: code = PermissionDenied desc = access denied for user@machinename: EOF
> --
> 13:22:31.361 unable to open repository: unable to open repository: unable to establish session for purpose=: error establishing session: unable to initialize session: rpc error: code = PermissionDenied desc = access denied for user@machinename: EOF, will keep trying until canceled. Sleeping for 16s
> 13:22:47.362 unable to check for updates: unable to open update state file: open /Users/username/Library/Application Support/kopia/repository.config.update-info.json: no such file or directory

**Comment by jkowalski** [comment] 2024-11-19 06:51
Can you try the latest test build from https://github.com/kopia/kopia-test-builds/releases/latest ? This will be part of 0.18.2 hot fix (around Wednesday).

**Comment by fcalvet** [comment] 2024-11-19 17:03
> Can you try the latest test build from https://github.com/kopia/kopia-test-builds/releases/latest ? This will be part of 0.18.2 hot fix (around Wednesday).

still the same issue after installing kopia-ui_20241119.0.64524_amd64.deb

**Comment by superbobdthm** [comment] 2024-11-20 14:05
I installed the nightly on one of my linux (ubuntu 24.04) boxes and I am still getting the error

`kopia-ui
[33880:1120/080433.953492:FATAL:setuid_sandbox_host.cc(163)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/KopiaUI/chrome-sandbox is owned by root and has mode 4755.
[1]    33880 trace trap (core dumped)  kopia-ui
`

**Comment by damienrg** [comment] 2024-11-20 14:14
This is related to `AppArmor`, you can create a specific profile in `/etc/apparmor.d/opt.KopiaUI.kopia-ui` containing:

```
abi <abi/4.0>,
include <tunables/global>
profile kopia-ui /opt/KopiaUI/kopia-ui flags=(unconfined) {
  userns,
}
```
You can then activate it with:

```
sudo apparmor_parser -r /etc/apparmor.d/opt.KopiaUI.kopia-ui
```

**Comment by jkowalski** [comment] 2024-11-20 16:35
There are 2 separate issues here, 

* Linux/Ubuntu - the right fix seems to be https://github.com/kopia/kopia/issues/4261#issuecomment-2488696607
* other OSes/permission issue - the test fix is in https://github.com/kopia/kopia-test-builds/releases, please report if that does fix the issue, so we can cut v0.18.2 soon.

**Comment by superbobdthm** [comment] 2024-11-20 17:05
Update the server to v20241119.0.64524 and ran the 0.17.0 client which was previously failing with 

`ERROR failed to open repository: unable to establish session for purpose=: error establishing session: unable to initialize session: rpc error: code = PermissionDenied desc = access denied for user@machinename: EOF
ERROR unable to initialize repository: unable to initialize repository: error opening repository: unable to open repository: unable to establish session for purpose=: error establishing session: unable to initialize session: rpc error: code = PermissionDenied desc = access denied for user@machinename: EOF`

I was now able to connect and run the backups.

**Comment by jkowalski** [comment] 2024-11-21 00:22
https://github.com/kopia/kopia/releases/tag/v0.18.2 is now out.

**Closed by jkowalski** 2024-11-21 00:22 UTC

**Comment by fpatron** [comment] 2024-11-22 06:59
I have a similar issue with 0.18.2 version when starting kopia-ui.
It starts and stops immediatly
```
laptop:~$ kopia-ui 
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
laptop:~$ 
```

**Comment by marco-pm** [comment] 2024-11-23 18:05
Same issue here, with all 0.18 versions (including 0.18.2). 
0.17 works.

**Comment by theHilikus** [comment] 2024-12-01 21:24
Me too. Same error in Ubuntu 24.04

I can confirm the AppArmor profile fixed it but is the best solution really to run unconfined. There has to be a less extreme solution

**Comment by fcalvet** [comment] 2024-12-11 10:13
As the initial error message suggests, ensuring correct file mode ie that chrome-sandbox has the setUID bit by running `sudo chmod 4755 /opt/KopiaUI/chrome-sandbox` solves the issue originally reported. I think it should be possible to fix it on the package side as well. No need touching AppArmor as far as I can tell.

**Comment by fcalvet** [comment] 2024-12-13 08:29
Actually in the .deb (control.tar.gz>postinst) it can be found as a change in between 17 and 18.x:
17.0: 
```
# SUID chrome-sandbox for Electron 5+
chmod 4755 '/opt/KopiaUI/chrome-sandbox' || true
```

18.x:
```
# Check if user namespaces are supported by the kernel and working with a quick test:
if ! { [[ -L /proc/self/ns/user ]] && unshare --user true; }; then
    # Use SUID chrome-sandbox only on systems without user namespaces:
    chmod 4755 '/opt/KopiaUI/chrome-sandbox' || true
else
    chmod 0755 '/opt/KopiaUI/chrome-sandbox' || true
fi
```

I can't find this in the code base, is it part of some automated electron/AppImage packaging ? 
[appears to be quite common issue among other apps](https://medium.com/@dadianas/solving-appimage-sandbox-issues-a-system-wide-fix-for-linux-users-1dd61f9c98a3)

**Comment by bobmorane06** [comment] 2025-01-17 15:31
FWIW, despite having installed kopia 0.18.2, I had to manually run `sudo chmod 4755 /opt/KopiaUI/chrome-sandbox` to get it working. 

The issue came up after I upgraded to KDE ubuntu 24.04 (Tuxedo OS 4) and switched from X11 to Wayland (not sure wich one caused the problem)

**Comment by gillius** [comment] 2025-01-17 18:15
I had the same issue on a completely new kopia-ui installation of 0.18.2 from apt repository on Kubuntu 24.10, with same solution to do the chmod. I am running Wayland, although I don't know if that matters.

**Comment by fcalvet** [comment] 2025-02-03 10:24
v0.19.0 doesn't have the issue, probably thanks to https://github.com/kopia/kopia/pull/4318
