### ISSUE TITLE
APT Repository signature not valid 

### ISSUE THREAD

**Issue by flavorgold1** [kopia/kopia#2949] opened 2023-04-17 02:13 UTC
I'm running Ubuntu 22.04.2 LTS.
I followed these directions: https://kopia.io/docs/installation/#linux-installation-using-apt-debian-ubuntu
It seems that the signature is not working.

```
Err:2 https://packages.kopia.io/apt stable InRelease
  The following signatures were invalid: EXPKEYSIG 2273699AFD56A556 Kopia Builder <builder@kopia.io>
Reading package lists... Done
W: GPG error: https://packages.kopia.io/apt stable InRelease: The following signatures were invalid: EXPKEYSIG 2273699AFD56A556 Kopia Builder <builder@kopia.io>
E: The repository 'http://packages.kopia.io/apt stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by jkowalski** [comment] 2023-04-17 05:37
This is a duplicate of https://github.com/kopia/kopia/issues/2947, closing this one.

**Closed by jkowalski** 2023-04-17 05:37 UTC
