### ISSUE TITLE
.kopiaignore pattern differs from .gitignore

### ISSUE THREAD

**Issue by phonovision** [kopia/kopia#571] opened 2020-08-30 22:52 UTC
internal/ignore/ignore.go states

> Package ignore implements ignoring files based on 'gitignore' syntax.

but there seem to be some differences between .gitignore and .kopiaignore patterns. Leading slashes are treated different, at least as far I can tell from calling _kopia snapshot estimate_.

I am not sure, if the differences are intended. If they are, I would be delighted if they would be documented. In that case I'd also like to know, how to achieve the same effect as a leading slash in [.gitignore pattern format](https://git-scm.com/docs/gitignore#_pattern_format).

If the differences are intended, it is necessary to take even more care on adopting a list like https://github.com/rubo77/rsync-homedir-excludes

I'm not sure how far this is covered by #492 or #496, therefore I will give an example:

#### FS layout
```
/tmp/kopia-test/.kopiaignore
/tmp/kopia-test/1GB.mp4
/tmp/kopia-test/A/1GB.mp4
/tmp/kopia-test/A/AA/1GB.mp4
/tmp/kopia-test/A/B/A/1GB.mp4
/tmp/kopia-test/B/A/1GB.mp4
```

#### Command: kopia snapshot estimate /tmp/kopia-test

1) .kopiaignore: `/A/` or `./A/`

    kopia scans everything, estimate is about 5GB. /A/... is  **not** ignored _(Expectation: /A ignored; /B/A/ and /B/A not ignored)_

2) .kopiaignore: `A/`

    Estimate is about 1GB. /A/... and /B/A/... are ignored _(meets expectations)_

3) .kopiaignore: `B/A/`

    Estimate is about 4GB. /A/B/A/... is  **not** ignored, /B/A/... is ignored _(Expectation: /A/B/A and /B/A both ignored)_

4) .kopiaignore: `/B/A/`

    kopia scans everything, estimate is about 5GB. /B/A/... is  **not** ignored _(Expectation: /A/B/A/ not ignored, /B/A ignored)_

**Comment by jkowalski** [comment] 2020-08-30 23:06
Thanks for the report. 

I'm going to need help on this, since I'm not too familiar with all intricacies of `.gitignore` - I originally implemented what seemeed like a reasonable subset of gitignore that worked for my needs, but apparently folks use it differently.

The main challenge here is that paths while snapshotting (as seen by the Uploader component) are always "virtual" (the root is always ".", which allows things like repository-to-repository migration which does not involve the filesystem) so resolving slash-prefixed paths is not going to be trivial.

**Comment by phonovision** [comment] 2020-08-30 23:53
Hi, thank you for for fast reply.

I'm not so sure if I could interpret your last paragraph correctly, but I will try to clarify my point a little bit more: A leading slash in .gitignore does not mean the actual (file-)system root; instead it takes the directory where .gitignore is placed as (relative) reference.

So for example if .gitignore is in ~, the difference between `/TEMP/` (only direct sub-directory named _TEMP_) and `TEMP/` (any driectory named _TEMP_) is the following:

1. `/TEMP/`
    ~/TEMP is ignored
    ~/Projects/Active/X/TEMP is **not** ignored

2. `TEMP/`
    ~/TEMP is ignored
    ~/Projects/Active/X/TEMP is ignored, too

**Comment by ruzickap** [comment] 2020-10-12 15:10
Another example taken from above:

```
$ mkdir -p /tmp/kopia-test/A
$ echo "Do Not backup this file" > /tmp/kopia-test/test1
$ echo "Backup this file" > /tmp/kopia-test/A/test1
$ echo "test1" > /tmp/kopia-test/.kopiaignore

$ tree /tmp/kopia-test
/tmp/kopia-test
├── A
│   └── test1                # <<<<< Backup this one
└── test1                    # <<<<< Do not backup this one

$ kopia repository create filesystem --path /tmp/backup_repo
$ kopia snapshot create /tmp/kopia-test
$ kopia snapshot list
$ kopia ls -l -r ke8b7d877c38a4da6aac66ecd0553ca71
-rw-r--r--            6 2020-10-12 17:03:48 CEST c1ef7e19480a9261590777454232cd24   .kopiaignore
drwxr-xr-x            0 2020-10-12 17:03:44 CEST kbfdf60f73fa25cfbfd28d83d0a2c4c1f  A/
```

There is no way how to exclude the first file `/tmp/kopia-test/test1` only and keep the second file `/tmp/kopia-test/A/test1` in the snapshot (because they have the same filename `test1`).

Currently both files `test1` are excluded from snapshot.

**Comment by alphaleonis** [comment] 2020-12-29 22:40
I'm not sure I understand the problem with the virtual filesystem you mention, since all paths in a .gitignore file are relative to the directory in which the .gitignore is located. But maybe I'm missing something?

The following three points from the [.gitignore specification](https://git-scm.com/docs/gitignore) illustrates the expected behavior rather clearly anyway:

* If there is a separator at the beginning or middle (or both) of the pattern, then the pattern is relative to the directory level of the particular `.gitignore` file itself. Otherwise the pattern may also match at any level below the `.gitignore` level.

* If there is a separator at the end of the pattern then the pattern will only match directories, otherwise the pattern can match both files and directories.

* For example, a pattern `doc/frotz/` matches `doc/frotz` directory, but not `a/doc/frotz` directory; however `frotz/` matches `frotz` and `a/frotz` that is a directory **(all paths are relative from the `.gitignore` file)**.

**Comment by alphaleonis** [comment] 2021-01-07 19:14
> 3. .kopiaignore: `B/A/`
>    Estimate is about 4GB. /A/B/A/... is  **not** ignored, /B/A/... is ignored _(Expectation: /A/B/A and /B/A both ignored)_

This is actually an incorrect expectation. If a path contains a directory separator in the middle, as this one does, it only matches relative to the ignore-file according to the gitignore spec (and also verified with git itself).  So the pattern `B/A/` is identical to `/B/A/`.  You need to use `**/B/A` to achieve the desired behavior in this case.

**Closed** 2021-01-08 16:13 UTC
Labels: enhancement, help wanted
