### ISSUE TITLE
symlinks are not preserved/restored

### ISSUE THREAD

**Issue by mbiebl** [kopia/kopia#543] opened 2020-08-16 14:36 UTC
Version: 0.6.1
OS: Debian buster / Linux

Hi,

I'm currently testing kopia for system wide backups. I noticed that after a backup / restore, all symlinks are missing.
E.g. from my /usr/bin directory
```
# find /usr/bin/ -type l | wc -l
194
```
After a `kopia restore k778b871e43f1ee3053f614b90b09ad68/usr/bin /var/tmp/restore`
```
# find /var/tmp/restore/ -type l | wc -l
0
```

**Comment by jkowalski** [comment] 2020-08-16 15:02
Yeah, this has not been implemented for some reason, which I can't recall.

BTW. `kopia restore` can produce a tar file which will preserve symlinks.

**Comment by mbiebl** [comment] 2020-08-16 15:07
> Yeah, this has not been implemented for some reason, which I can't recall.

It would probably be a good idea to implement that or at least document that limititation as this was unexpected to me.
 
> BTW. `kopia restore` can produce a tar file which will preserve symlinks.

Ah, good to know. How can I do that? I can't seem to find any documentation in that regard.

**Comment by jkowalski** [comment] 2020-08-16 15:11
Simply `kopia restore xxxx file.tar`. To restore to a directory whose name ends with .tar (unusual) pass `--mode=local`

**Comment by jkowalski** [comment] 2020-09-02 00:26
Dupe of #474

**Closed by jkowalski** 2020-09-02 00:26 UTC
Labels: enhancement, good first issue, help wanted
