### ISSUE TITLE
Kopia(UI): Fails to close TCP connections and eventually causes unrelated processes to fail

### ISSUE THREAD

**Issue by typpos** [kopia/kopia#2453] opened 2022-09-27 10:23 UTC
Informal: While running KopiaUI, after some time Google Chrome fails to open new web pages ("no internet" / "unable to reach dns server"). An already running downloader application continues to download just fine. Ping to google.com works fine. When I quit KopiaUI, Chrome works again. This may be related to KopiaUI repeatedly trying to connect to a storage target that is currently offline.

I believe KopiaUI somehow depletes available TCP connections or a related OS resource.

I monitored Kopia/KopiaUI with SysInternals Process Monitor which shows a repeating sequence of 3 TCP Opens (cryptomator-vault) followed by only 2 TCP Closes, interspersed with the usual TCP Accept, sends, and receives.

When I quit KopiaUI (Taskbar > KopiaUI Icon > Quit), Process Monitor shows a sequence of over 24,000 TCP Receive  & TCP Disconnect pairs against kopia.exe. 

--

Version v0.11.3 https://github.com/kopia/kopia/commit/317cc36892707ab9bdc5f6e4dea567d1e638a070 kopia/htmlui fcd217241a877fdba53a3afa72d68b73f14fd8c2 built on Thu Jul 7 03:07:56 UTC 2022 fv-az196-146

Windows 10 Pro x64, 10.0.19043

**Comment by riedel** [comment] 2022-11-27 09:19
seems to be a duplicate of #2226 . I can confirm that this is still happening with recent versions and quite annoying!

**Comment by riedel** [comment] 2023-06-04 08:42
I confirmed this by connecting to my vacuum cleaners network (note: I only use samba as repo, so all connections are towards a presumably hanging kopia server process from the UI)

This is what I get on windows. Note the drop of connection (I reestablished the connection which made the network drive share available again).

`>bash -c 'while printf "%(%X)T kopia sockets: "; do netstat -aonb | grep -a -B1 kopia|wc -l; sleep 10 ; done '               
10:36:46 kopia sockets: 618                                                                                                                     
10:36:56 kopia sockets: 624                                                                                                                     
10:37:07 kopia sockets: 632                                                                                                                     
10:37:17 kopia sockets: 638                                                                                                                     
10:37:27 kopia sockets: 644                                                                                                                     
10:37:37 kopia sockets: 652                                                                                                                     
10:37:47 kopia sockets: 658                                                                                                                     
10:37:57 kopia sockets: 666                                                                                                                     
10:38:08 kopia sockets: 9                                                                                                                                                                                                                                                                       10:38:18 kopia sockets: 9 `

**Comment by riedel** [comment] 2023-06-04 08:54
I not familiar with the build process (might try later), but is seems to  me adding a timeout option to https requests might be a smart thing to do eg here:
https://github.com/kopia/kopia/blob/3622b58554e26bc14db2c798528f5203d17b1f6a/app/public/server.js#L75-L83

**Comment by riedel** [comment] 2023-06-04 10:47
Steps to reproduce consistently for me:
 1. start KopiaUI with network connected and a repository on a network share
 1. connect to a network where the network share is not available
 1.  press refresh button in "My repository" page
 1. see TCP sockets increasing

**Comment by riedel** [comment] 2023-06-04 12:52
The core of the problem is that the API may block on some request due to resource unavailability like on `sync`. Now the client continues to call e.g. `task-summary` and `sources` to refresh the UI. This seems to lead to a ton of pending requests that all open a TCP connection. At some time the OS limit on connections is reached. There must be a smarter way to handle the problem actually in the API server...

**Comment by kahojyun** [comment] 2023-07-08 21:13
I have also encountered similar problems. Previously, my computer was unable to open any web pages about every one week, and it only returned to normal after restarting. This time, I found out that Kopia has used up all the ports on the computer through the `netstat -ab` command. The output is as follows:

```
  Proto  Local Address          Foreign Address        State
  ...
  TCP    127.0.0.1:50552        kubernetes:61497       ESTABLISHED
 [KopiaUI.exe]
  TCP    127.0.0.1:50553        kubernetes:61497       ESTABLISHED
 [KopiaUI.exe]
  TCP    127.0.0.1:50554        kubernetes:61497       ESTABLISHED
 [KopiaUI.exe]
  TCP    127.0.0.1:50555        kubernetes:61497       ESTABLISHED
 [KopiaUI.exe]
  ...
```
I'm using kopiaUI v0.13.0 on windows 11.

**Comment by stewartadam** [comment] 2024-02-18 00:15
I can reproduce this on MacOS as well, start KopiaUI and then disable network interfaces and a new connection is created every few seconds:

```sh
sudo lsof -Pn -i4 | grep -e ssh -e kopia
```

Eventually sockets are exhausted and new processes will fail to start.

**Comment by jkowalski** [comment] 2024-02-18 03:04
@stewartadam what is your backend in this case? I think it's the issue with specific backends, does not reproduce with S3.

**Comment by typpos** [comment] 2024-02-18 04:41
In case it helps, my Kopia Repo was on an external usb drive that was not plugged in. Files were backed up from local file system and another Windows PC via a network share.

**Comment by stewartadam** [comment] 2024-02-18 04:45
> @stewartadam what is your backend in this case? I think it's the issue with specific backends, does not reproduce with S3.

Interesting! I'm using SFTP.

**Closed** 2024-02-21 05:23 UTC
Labels: bug, app, htmlui, robustness
